languageCode = "en-au"
title = "Hello! Welcome!"
theme = 'hugo-blog-awesome'
author = "Aria Dolatabadian"
copyright = "Copyright © 2023, Aria Dolatabadian"
enableRobotsTXT = true
defaultContentLanguage = "en-aus"
disableKinds = ["taxonomy"]
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

# ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

# for code highlighting

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Aria Dolatabadian's blog"
  defaultColor = 'dark'

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"




[[params.socialIcons]]
name = "github"
url = "https://github.com/Aria-Dolatabadian/"


[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/ariadolatabadian/"


[tableOfContents]
startLevel = 2 # ToC starts from H2
endLevel = 4 # ToC ends at H4
ordered = false # generates <ul> instead of <ol>
